### ISSUE TITLE
Include ELKI for some 20+ additional algorithms

### ISSUE THREAD

**Issue by kno10** [Minqi824/ADBench#10]
ELKI, which can easily be invoked from command line, provides many additional algorithms missing from this benchmark, such as:

* DB Outlier
* HilOut
* KNNDD (not the same as KNN Outlier)
* KNNSOS
* KNN-weight
* Local Isolation Coefficient
* ODIN
* Reference-Based outlier detection
* SOS
* HySort OD
* ALOCI
* INFLO
* KDEOS
* LDF
* LDOF
* LOCI
* LoOP
* SimplifiedLOF
* VarianceOfVolume
* ABOD / FastABOD, LB-ABOD
* IDOS
* ISOS
* LID
* GLOSH for HDBSCAN*

In other cases, it may be desirable to compare the performance of different implementations:
* Isolation Forest
* kNN Outlier
* LOF
* COF
* CBLOF
Because sometimes one implementation may be better than another.

**Comment by Minqi824** [comment]
Thank you for your valuable advice! In the future, we plan to include more algorithms (both shallow machine learning algorithms and deep learning algorithms) in our ADBench, to analyze different AD algorithms from a more comprehensive perspective.
