### ISSUE TITLE
ALOI dataset description

### ISSUE THREAD

**Issue by blackDZS** [Minqi824/ADBench#12]
I don't find any description of ALOI dataset in ADBench paper. And only an inference link of paper https://arxiv.org/pdf/1503.01158.pdf , and I can't find "ALOI" key words in this paper. Can you give more description about ALOI Dataset ?

**Comment by Minqi824** [comment]
Thanks for following our paper. The description of ALOI datasets is in the **appendix** of our ADBench paper. Please refer to the link: https://openreview.net/attachment?id=foA_SFQ9zo0&name=supplementary_material

**Comment by blackDZS** [comment]
Thanks for your reply, I find the data source and processing method in https://www.dbs.ifi.lmu.de/research/outlier-evaluation/DAMI/literature/ALOI/ from your inference paper.
