### ISSUE TITLE
Paralle computing to tackel large-scale data.

### ISSUE THREAD

**Issue by SUFEHeisenberg** [Minqi824/ADBench#5]
Great and Enormours Work!
Do we have paralle computing setting to process large-scale data? Cause in reality, big data condition is more common and difficult.

**Comment by Minqi824** [comment]
Thanks for your kind suggestion! In ADBench, one can parallelly reproduce our results by setting the parallel option (i.e., "unsupervise", "semi-supervise" or "supervise") in the [code](https://github.com/Minqi824/ADBench/blob/main/run.py). For more complex algorithms like FTTransformer, we also support the GPUs implementation for accelerating the training process.
